version: 2
updates:
  - package-ecosystem: "maven"      # Specify Gradle as the package ecosystem
    directory: "/"                  # Root directory of the project
    schedule:
      interval: "weekly"   
