name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
  schedule:
    - cron: '0 4 * * 1'  # Optional: run once weekly in case PRs haven't been merged yet

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Automatically merge PRs
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          # Auto-merge pull requests with a specific label (e.g., "dependencies" or "snyk").
          label: 'dependabot'
          token: ${{ secrets.GITHUB_TOKEN }}
